### ISSUE TITLE
Plugin naming conflict

### ISSUE THREAD

**Issue by harlows** [danielstorey/adapt-reveal#2]
Thanks for providing the schema. The plugin installs correctly into the Authoring Tool, however, it seems to conflict with [LearningPool's similarly titled Reveal component](https://github.com/LearningPool/adapt-contrib-reveal). Is it possible to rename your extension? It may be as easy as choosing a unique component name in the bower.json file.

**Comment by hbaileylxd** [comment]
Yes I agree - it broke my LP Reveal plugin so I've had to remove yours until this is fixed. Thanks!

**Comment by danielstorey** [comment]
Ah boo that's no good - I'll fix it tonight!

**Comment by danielstorey** [comment]
[**Please see adapt-expose**](https://github.com/danielstorey/adapt-expose)
